spring:
  application:
    name: user-service



  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

logging:
  level:
    org.springframework.security: DEBUG